spring:
  application:
   name: ${vcap.application.name}

eureka:
  instance:
    hostname: ${vcap.application.uris[1]}
    nonSecurePort: 80
  client:		
    serviceUrl:		
      defaultZone: ${vcap.application.uris[1]}
