spring:
  application:
   name: ${vcap.application.name}

eureka:
  instance:
    hostname: http://7ZlPXXnf22no:xucmM4hozVEG@eureka-c8b50f49-802b-426b-ab52-c54c3a39799a.south.fe.pivotal.io
    nonSecurePort: 80
