message: "Olá mundo!"
spring:
  application:
   name: hello-service
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    defaultZone: ${vcap.services.eureka-service.credentials.uri}
