spring:
  application:
   name: hello-service-client
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka-server-demo.cfapps.io/eureka/
