message: "Victor!"
spring:
  application:
   name: hello-service
eureka:
  instance:
    hostname: http://eureka-server-net.cfapps.io/eureka/
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}