message: "Olá NET!"
spring:
  application:
   name: hello-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-net.cfapps.io/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
